export enum ColumnDisplayType {
  NUMBER = 'number',
  FLOAT = 'float',
  IMAGE = 'image',
  IMAGES = 'images',
  BOOLEAN = 'boolean',
  USER_WITH_IMAGE = 'user-with-image',
  USER_INVITE = 'user-invite',
  SWITCH = 'switch',
  STATUS = 'status',
  USERS = 'users',
  DATE = 'date',
  DATE_TIME = 'date-time',
  DATE_RANGE = 'date-range',
  DATE_RANGE_TIME = 'date-time-range',
  TIME = 'time',
  LINK = 'link',
  BUTTON = 'button',
  HTML = 'HTML'
}
